[package]
name = "burelom-net"
version = "0.1.0"
edition = "2021"

[features]
tokio = [
  "dep:tokio",
  "dep:log",
  "dep:embassy-sync",
  "log"
]
embassy = [
  "dep:embassy-time",
  "dep:embassy-executor",
  "dep:defmt",
  "dep:embassy-sync",
  "dep:embassy-futures",
  "defmt"
]
log = []
defmt =[]

[dependencies]
defmt = { workspace = true, optional = true }
log = { workspace = true, optional = true }
async-trait.workspace = true
anyhow.workspace = true
const-hex.workspace = true
prost.workspace = true
prost-types.workspace = true
bon.workspace = true
async-oneshot = "0.5.9"
hashbrown = "0.17.1"
async-channel.workspace = true
enumset.workspace = true
tokio = {workspace = true, optional = true}
embassy-time = { version = "0.5.0", features = ["defmt"], optional = true }
embassy-executor = { version = "0.10.0", features = ["defmt"], optional = true }
embassy-sync = { version = "0.8.0", features = ["defmt"], optional = true }
embassy-futures = { version = "0.1.2", features = ["defmt"], optional = true }
heapless = "0.9.3"


[build-dependencies]
prost-build = "0.14"